### PR TITLE
Update: Submodule commits for SkiROS2

### PR DESCRIPTION
**Pull request by matthias-mayr**
- Problem skills for the participants
- Solution skills for all problems
- Docs for problem 1-4
- Planning integration with skills, but unfinished problem & solution PDDL files

### CODE REVIEW

**Comment by matthias-mayr** [comment]
I'll merge this right away since it only includes the SkiROS2 repos and I want to give this to some people to try it out.

It would be great if other people could follow the instructions as well and open issues in https://github.com/matthias-mayr/skiros2_pyrobosim_lib. Thanks in advance.

**Comment by sea-bass** [comment]
I tested this and everything ran.

Here are my comments:

* Definitely ran into this: https://github.com/matthias-mayr/skiros2_pyrobosim_lib/issues/3
* My GUI would often freeze and I got the Ubuntu ("Force Quit" or "Wait" dialog). Just waiting was fine in the long run, but the GUI generally was not too responsive.
* In a few cases, the GUI never loaded and froze on startup. But restarting was fine.
* Forgetting the above issues, Problems 1 and 3 seemed to complete properly, but not 2 and 4. Somehow the robot never opened the dumpster -- probably the same issue as https://github.com/matthias-mayr/skiros2_pyrobosim_lib/issues/7?
* Generally, there were very long waits between any actions executing, and the GUI seemed to go through an entire "refresh" until a skill started running again. Is this normal?

**Comment by matthias-mayr** [comment]
> Here are my comments:

Thanks a lot.

> In a few cases, the GUI never loaded and froze on startup. But restarting was fine.

@p-rosit has this as well. I don't get that though. I wonder what could cause it. I noticed a general slowdown if a lot of ROS 2 traffic happens in a network, but at least for Pontus that should not happen. Hard to reproduce here though.

> Forgetting the above issues, Problems 1 and 3 seemed to complete properly, but not 2 and 4. Somehow the robot never opened the dumpster -- probably the same issue as https://github.com/matthias-mayr/skiros2_pyrobosim_lib/issues/7?

I assume that you ran the solutions and shall check them again. Obviously the problem skills do not solve the tasks.

> Generally, there were very long waits between any actions executing, and the GUI seemed to go through an entire "refresh" until a skill started running again. Is this normal?
>> Update: This seems to be just the wm_set_relation node taking a long time.

Correct observation. With ROS 2 this seems to have become really slow.

**Comment by matthias-mayr** [comment]
@sea-bass thanks for the feedback. I indeed forgot to run the skills manually again after I added a postcondition.  
#71 addresses the scenarios that did not complete.

**Pull request merged**
