### PR TITLE
Update READMEs with more information

### LINKED ISSUE #52: Fails to find Package 'delib_ws_p1' while running setup instructions for ROSCon 2024 workshop on Deliberation Technologies
Hello,

I'm trying out the setup instructions in advance of the ROSCon 2024 workshop on Deliberation technologies, because I wanted to see if could run it in a Docker container on my Macbook.

However, before I could fully test it out, I found that the 4th step in the Setup instructions (https://github.com/ros-wg-delib/roscon24-workshop/blob/main/README.md) fails with the following error: 

`root@docker-desktop:/delib_ws# ros2 run delib_ws_p1 run`
`Package 'delib_ws_p1' not found`

I suspect that the package has been renamed. 
Could you take a look and update the instructions?
 
Thanks.

### PR DESCRIPTION
**Pull request by sea-bass**
This PR updates the READMEs with more detailed information about the setup, dev environment, and technologies we are showing the workshop. It also rearranges things into the subfolder READMEs as appropriate.

I also updated the Markdown lint to a tool that runs in pre-commit, so there is only less CI job, and added a `media` subfolder to place images into.

I would suggest keeping the review here on high-level structure, and biasing towards getting something merged. Then, everyone can adding their own extra information in the right places in follow-up PRs.

Closes #52

### CODE REVIEW

**Comment by sea-bass** [comment]
Good feedback @dcconner -- I've added a System Requirements section that strongly recommends Ubuntu 22.04/24.04 and gives lightweight steps for other host OSes to set up VMs otherwise. Plus the Docker install steps.

**Comment by dcconner** [comment]
On the https://docs.docker.com/engine/install/ page, the first link is for [Docker Desktop for Linux](https://docs.docker.com/desktop/install/linux/)

On our page, we might want to be very clear that we prefer "Docker Engine" on Ubuntu, and do NOT click the "Desktop" link.  I presume we want them to click through to https://docs.docker.com/engine/install/ubuntu/

So, maybe put that link on our page.

**Comment by sea-bass** [comment]
I've gone through this whole conundrum of "which of the 75 ways should I document installation of Docker?" for previous professional work.

The conclusion of many iterations was tell people they are responsible for having Docker commands work without `sudo`, and once they are able to do that, they are good to move on.

**Comment by dcconner** [comment]
Then maybe we should set expectations .  Add a note at top that says to do set up instructions (below) *PRIOR* to coming to the workshop, and that commands work, in your segue maybe show the "docker hello world" command.

Maybe provide a link to *Troubleshooting* page or link to submit issues with suggested tags?

I just fear getting there Monday and 30% of class can't get Docker working, so providing explicit checklist  for Sunday afternoon may be warranted.

**Review by Oberacda — APPROVED** [review]

**Review by ct2034 — APPROVED** [review]
Love these changes. Thanks for putting in the restructuring work

**Comment by ct2034** [comment]
I would be fine with merging this. If someone need changes in the part concerning their technology, a follow-up PR would be a good approach. 
Are you fine @dcconner with that? Technically, your review is still open.

**Review by dcconner — APPROVED** [review]

**Pull request merged**
